name: My-acition
on:
  push:
    branches: 
      -master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Print Hello Message
      run: echo "hello"
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
