name: C Workflow
 
on: [push, pull_request]

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Git clone repos
      uses: actions/checkout@v1
      
    - name: valgrind
      run: |
        ls -la 
        sudo apt-get -qy install lcov
        sudo apt-get install -y valgrind
        sudo apt install valgrind
        
    - name: List current folder 
      run: |
        cd lab_1 
        make
        chmod a+x ./main
        chmod a+x ./tests
        valgrind  ./main
        valgrind ./tests
        cd ..
        cd lab_2
        cd first_task
        make 
        chmod a+x ./main
        chmod a+x ./tests
        valgrind  ./main 3 2 
        valgrind ./tests
        cd .. 
        cd ..
        cd lab_3
        make
        chmod a+x ./main
        chmod a+x ./tests
        valgrind  ./main
        valgrind ./tests 
        cd ..
        cd lab_4 
        cd 'first_task(4.1)'
        ls -la
        make
        chmod a+x ./main
        chmod a+x ./tests
        valgrind  ./main
        valgrind ./tests 
        cd .. 
        cd second_task
        make
        chmod a+x ./main
        chmod a+x ./tests
        valgrind  ./main
        valgrind ./tests
        cd ..
        cd ..
        cd lab_5 
        make
        chmod a+x ./main
        chmod a+x ./tests
        valgrind  ./main
        valgrind ./tests
        cd ..
        cd lab_6 
        make
        chmod a+x ./main
        chmod a+x ./tests
        valgrind  ./main
        valgrind ./tests
        cd ..
        cd lab_7
        make
        gcov -abcfu test.cpp Student.cpp workflow.cpp
    - name: Fetch
      uses: actions/checkout@master   
    - name: Upload
      uses: codecov/codecov-action@v1
      with:
        files: |
               ./lab_7/workflkow.cpp.gcov
               ./lab_7/Student.cpp.gcov
              

