name: C Workflow
 
on: [push, pull_request]

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Git clone repos
      uses: actions/checkout@v1
      
 
    - name: List current folder 
      run: |
        cd lab_1 
        ls -la
        make
        ls -la 
        cd ..
        cd lab_3
        gcc -o tests tests.c
    - name: valgrind
      run: |
        ls -la 
        sudo apt-get -qy install lcov
        sudo apt-get install -y valgrind
        sudo apt install valgrind
        ls -la
        cd lab_1
        ls -la
        chmod a+x ./main
       
        valgrind  ./main
        ls -la 
        chmod a+x ./tests
        valgrind ./tests
        ls -la 
        cd ..
        cd lab_3
         ls -la
        cd lab_1
        ls -la
        
        chmod a+x ./tests
        valgrind ./tests
        ls -la 
