name: C Workflow
 
on: [push, pull_request]

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Git clone repos
      uses: actions/checkout@v1
      
    - name: valgrind
      run: |
        ls -la 
        sudo apt-get -qy install lcov
        sudo apt-get install -y valgrind
        sudo apt install valgrind
        
    - name: make all files 
      run: |
        cd lab_1 
        make
        chmod a+x ./main
        chmod a+x ./tests
        valgrind  ./main
        valgrind ./tests
        cd ..
        cd lab_2
        cd first_task
        make 
        chmod a+x ./main
        chmod a+x ./tests
        valgrind  ./main 3 2 
        valgrind ./tests
        cd .. 
        cd ..
        cd lab_3
        make
        chmod a+x ./main
        chmod a+x ./tests
        valgrind  ./main
        valgrind ./tests 
        cd ..
        cd lab_4 
        cd 'first_task(4.1)'
        ls -la
        make
        chmod a+x ./main
        chmod a+x ./tests
        valgrind  ./main
        valgrind ./tests 
        cd .. 
        cd second_task
        make
        chmod a+x ./main
        chmod a+x ./tests
        valgrind  ./main
        valgrind ./tests
        cd ..
        cd ..
        cd lab_5 
        make
        chmod a+x ./main
        chmod a+x ./tests
        valgrind  ./main
        valgrind ./tests
        cd ..
        cd lab_6 
        make
        chmod a+x ./main
        chmod a+x ./tests
        valgrind  ./main
        valgrind ./tests
    - name: Test
      run: |
       
       ls -la 
       cd lab_7
       ls -la
       g++ -ftest-coverage -fprofile-arcs -O0 -o test test.cpp Student.cpp workflow.cpp
       ./test
       gcov -abcfu workflow.cpp Student.cpp 
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
       files: |
         ./lab_7/Student.cpp.gcov
         ./lab_7/workflow.cpp.gcov

        
