name: C Workflow
 
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Print Hello Message
      run: echo "hello world"
      
    - name: List current folder 
      run: ls -la 
      
    - name: Git clone repos
      uses: actions/checkout@v1
      
    - name: List current folder 
      run: ls -la 
      
    - name: valgrind
      run: |
        sudo apt-get install -y valgrind
        valgrind -v --leak-check=full --show-leak-kinds=all ./bin

    - name: Fetch
      uses: actions/checkout@master
    - uses: actions/checkout@v2
    - name: compile and test
      run: |
        for d in */ ; do
        make -C "%d"
        done
 
