


name: C Workflow
 
on: [push, pull_request]

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Print Hello Message
      run: echo "hello"

      
    - name: Git clone repos
      uses: actions/checkout@v1
      
    - name: List current folder 
      run: ls -la 
    - name: List current folder 
      run: |
        cd lab_1 
        ls -la
        make
        ls -la 
    
    - name: C++ code linter (clang-tidy and cppcheck)
      uses: smay1613/cpp-linter-action@0.0.2

