name: C Workflow
 
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch
      uses: actions/checkout@master
    - uses: actions/checkout@v2
    - name: compile and test
      run: |
        for d in */ ; do
        make -C "%d"
        done
    - name: valgrind
      run: |
        sudo apt-get install -y valgrind
        valgrind -v --leak-check=full --show-leak-kinds=all ./bin
