name: built-actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: compiling and testing lab 1
      working-directory: ./lab_1
      run: make 
      
